### ISSUE TITLE
Current `dynlib`-only approach might be insufficient, need `header` 

### ISSUE THREAD

**Issue by Vindaar** [SciNim/nimcuda#27]
# Table of Contents

1.  [The initial Nim program](#orge035e50)
2.  [The same code in C](#orgfae8ce8)
3.  [Comparing the PTX](#orge200b90)
4.  [Generate the CUBIN](#orgae5e7c0)
5.  [A CUBIN loader & runner in C](#orga5ffc90)
6.  [A CUBIN loader in Nim](#orgd19ee52)
7.  [A standalone example](#org69b5e20)
8.  [Applying this to `nimcuda`](#org3e0c1f3)

**NOTE**: I've written the below probably more for myself than anyone
else, to understand what I actually did to figure out what the heck
went wrong.

I'm prefacing this issue by saying that I may be missing
something. But I've come to the conclusion that our current approach
of wrapping CUDA is fundamentally flawed, because we only use `cdecl`,
`importc` and `dynlib`. I think we must use `header: "foo.h"` in
addition.

Essentially, I've been toying around a lot with `nimcuda` the last
week. I've essentially written a tiny macro DSL to Nim "compile-time
compile" Nim code to a CUDA string. At some point I tried to just
insert a `printf` into the CUDA code, which is nowadays possible. A
single `printf` breaks the library.

Over quite a few hours I've now finally nailed it down to the omission
of the `header` pragma.

In short, I'm able to load a CUBIN file in C, compile via `gcc` and
have it load & run successfully. However, loading the identical file
from a (seemingly identical) Nim program causes a
`CUDA_ERROR_INVALID_IMAGE` error.

<a id="orge035e50"></a>

# The initial Nim program

Let's start by looking at the (ultra reduced and basic) Nim program,
which succeeds / fails with `nimcuda` depending on whether a `printf`
is present.

```nim
import nimcuda/cuda12_5/[nvrtc, check, cuda]

const kernel_source = """
extern "C" __global__ void warpTest(int* output) {
    printf("hello"); // comment out the printf and it works
    int tid = ((blockIdx.x * blockDim.x) + threadIdx.x);
    if (blockDim.x == 32) {
        output[tid] = 1;
    }
}
"""

proc main =
  # Initialize CUDA
  var res = cuInit(0)
  if res != CUDA_SUCCESS:
    var error_str: cstring
    check cuGetErrorString(res, cast[cstringArray](addr error_str))
    echo "CUDA init failed: ", error_str
    quit(1)

  var device: CUdevice
  var context: CUcontext
  res = cuDeviceGet(addr device, 0)
  if res != CUDA_SUCCESS: quit(1)
  res = cuCtxCreate(addr context, 0, device)
  if res != CUDA_SUCCESS: quit(1)

  # Create program
  var prog: nvrtcProgram
  var compileResult = nvrtcCreateProgram(addr prog, kernel_source,
                                        "kernel.cu", 0, nil, nil)
  if compileResult != NVRTC_SUCCESS:
    echo "Program creation failed"
    quit(1)

  # Compile
  const opts = [cstring "--gpu-architecture=sm_61"]
  compileResult = nvrtcCompileProgram(prog, 1, cast[cstringArray](addr opts[0]))
  if compileResult != NVRTC_SUCCESS:
    var logSize: csize_t
    check nvrtcGetProgramLogSize(prog, addr logSize)
    var log = newString(logSize)
    check nvrtcGetProgramLog(prog, cstring log)
    echo "Compilation failed: ", log
    quit(1)

  # Get PTX
  var ptxSize: csize_t
  check nvrtcGetPTXSize(prog, addr ptxSize)
  var ptx = newString(ptxSize)
  check nvrtcGetPTX(prog, cstring ptx)

  writeFile("kernel_nim.ptx", ptx)

  # Load module
  var modul: CUmodule
  res = cuModuleLoadData(addr modul, cstring ptx)
  if res != CUDA_SUCCESS:
    var error_str: cstring
    check cuGetErrorString(res, cast[cstringArray](addr error_str))
    echo "Module load failed: ", error_str
    quit(1)

  # Get function
  var kernel: CUfunction
  res = cuModuleGetFunction(addr kernel, modul, "warpTest")
  if res != CUDA_SUCCESS: quit(1)

  # Allocate memory
  var dOutput: CUdeviceptr
  res = cuMemAlloc(addr dOutput, sizeof(cint) * 32)
  if res != CUDA_SUCCESS: quit(1)

  # Launch kernel
  var args = [cast[pointer](addr dOutput)]
  res = cuLaunchKernel(kernel,
                       1, 1, 1,    # grid
                       32, 1, 1,   # block
                       0, nil,       # shared mem, stream
                       addr args[0], nil) # args, extra
  if res != CUDA_SUCCESS:
    var error_str: cstring
    check cuGetErrorString(res, cast[cstringArray](addr error_str))
    echo "Kernel launch failed: ", error_str
    quit(1)

  check cuCtxSynchronize()

  # Cleanup
  check cuMemFree(dOutput)
  check cuModuleUnload(modul)
  check cuCtxDestroy(context)

main()
```

Depending on whether the `printf` line is present in the CUDA kernel
the code either succeeds or breaks.

We save the PTX to a file `kernel_nim.ptx` so that we can compile it to CUBIN using
`nvlink`.

<a id="orgfae8ce8"></a>

# The same code in C

Here's the exact same code from C. We write a `kernel_c.ptx` file in
this case. It works perfectly fine with and without the `printf`
statement being present.

```c
#include <cuda.h>
#include <nvrtc.h>
#include <stdio.h>

const char* kernel_source = R"(
extern "C" __global__ void warpTest(int* output) {
    printf("hello"); // works with and without printf!
    int tid = ((blockIdx.x * blockDim.x) + threadIdx.x);
    if (blockDim.x == 32) {
        output[tid] = 1;
    }
}
)";

int main() {
    // Initialize CUDA
    CUresult res = cuInit(0);
    if (res != CUDA_SUCCESS) {
        const char* error_str;
        cuGetErrorString(res, &error_str);
        printf("CUDA init failed: %s\n", error_str);
        return 1;
    }

    CUdevice device;
    CUcontext context;
    res = cuDeviceGet(&device, 0);
    if (res != CUDA_SUCCESS) return 1;
    res = cuCtxCreate(&context, 0, device);
    if (res != CUDA_SUCCESS) return 1;

    // Create program
    nvrtcProgram prog;
    nvrtcResult compileResult = nvrtcCreateProgram(&prog, kernel_source,
                                                  "kernel.cu", 0, NULL, NULL);
    if (compileResult != NVRTC_SUCCESS) {
        printf("Program creation failed\n");
        return 1;
    }

    // Compile
    const char* opts[] = {"--gpu-architecture=sm_61"};
    compileResult = nvrtcCompileProgram(prog, 1, opts);
    if (compileResult != NVRTC_SUCCESS) {
        size_t logSize;
        nvrtcGetProgramLogSize(prog, &logSize);
        char* log = malloc(logSize);
        nvrtcGetProgramLog(prog, log);
        printf("Compilation failed: %s\n", log);
        free(log);
        return 1;
    }

    // Get PTX
    size_t ptxSize;
    nvrtcGetPTXSize(prog, &ptxSize);
    char* ptx = malloc(ptxSize);
    nvrtcGetPTX(prog, ptx);

    printf("PTX size: %zu\n", ptxSize);
    printf("PTX start: %.100s\n", ptx);

    FILE* f = fopen("kernel_c.ptx", "w");
    fwrite(ptx, 1, ptxSize, f);
    fclose(f);

    // Load module
    CUmodule module;
    res = cuModuleLoadData(&module, ptx);
    if (res != CUDA_SUCCESS) {
        const char* error_str;
        cuGetErrorString(res, &error_str);
        printf("Module load failed: %s\n", error_str);
        return 1;
    }

    // Get function
    CUfunction kernel;
    res = cuModuleGetFunction(&kernel, module, "warpTest");
    if (res != CUDA_SUCCESS) return 1;

    // Allocate memory
    CUdeviceptr d_output;
    res = cuMemAlloc(&d_output, sizeof(int) * 32);
    if (res != CUDA_SUCCESS) return 1;

    // Launch kernel
    void* args[] = {&d_output};
    res = cuLaunchKernel(kernel,
                        1, 1, 1,    // grid
                        32, 1, 1,   // block
                        0, 0,       // shared mem, stream
                        args, 0);   // args, extra
    if (res != CUDA_SUCCESS) {
        const char* error_str;
        cuGetErrorString(res, &error_str);
        printf("Kernel launch failed: %s\n", error_str);
        return 1;
    }

    res = cuCtxSynchronize();
    if (res != CUDA_SUCCESS) return 1;

    // Cleanup
    free(ptx);
    cuMemFree(d_output);
    cuModuleUnload(module);
    cuCtxDestroy(context);

    return 0;
}
```

We compile this file with:

    gcc -I/usr/local/cuda-12.6/targets/x86_64-linux/include -L/usr/local/cuda-12.6/targets/x86_64-linux/lib -o rt_printf rt_printf.c -lcuda -lnvrtc

<a id="orge200b90"></a>

# Comparing the PTX

While you have to believe me now, the generated PTX is identical. So
from here on we'll just continue from a CUBIN file.

<a id="orgae5e7c0"></a>

# Generate the CUBIN

To generate the CUBIN from the PTX file:

    nvlink -m64 --arch=sm_61 kernel_nim.ptx -lcudadevrt -o kernel_nim.cubin

Obviously, given that the PTX is the same, the generated CUBIN is the
same too.

<a id="orga5ffc90"></a>

# A CUBIN loader & runner in C

Let's look at a simple loader a CUBIN file and execute that kernel in
C:

```c
#include <cuda.h>
#include <stdio.h>

int main() {
    CUdevice device;
    CUcontext context;
    CUmodule module;
    CUfunction kernel;
    CUdeviceptr output;

    // Init
    cuInit(0);
    cuDeviceGet(&device, 0);
    cuCtxCreate(&context, 0, device);

    // Load the CUBIN
    if (cuModuleLoad(&module, "kernel_nim.cubin") != CUDA_SUCCESS) {
        printf("Failed to load module\n");
        return 1;
    }

    if (cuModuleGetFunction(&kernel, module, "warpTest") != CUDA_SUCCESS) {
        printf("Failed to get function\n");
        return 1;
    }

    // Allocate GPU memory
    cuMemAlloc(&output, sizeof(int) * 32);

    // Launch kernel
    void* args[] = {&output};
    cuLaunchKernel(kernel,
                   1, 1, 1,    // Grid dimensions
                   32, 1, 1,   // Block dimensions
                   0, 0,       // Shared memory and stream
                   args, 0);   // Arguments and extra

    cuCtxSynchronize();

    // Optional: read back results
    int host_output[32];
    cuMemcpyDtoH(host_output, output, sizeof(int) * 32);

    // Print first few results
    for(int i = 0; i < 10; i++) {
        printf("%d ", host_output[i]);
    }
    printf("\n");

    // Cleanup
    cuMemFree(output);
    cuModuleUnload(module);
    cuCtxDestroy(context);

    return 0;
}
```

Compiling and running it 

    gcc -I/usr/local/cuda-12.6/targets/x86_64-linux/include -L/usr/local/cuda-12.6/targets/x86_64-linux/lib -o execute_cubin execute_cubin.c -lcuda

works perfectly fine. So the "Nim generated" kernel runs perfect,
despite not being loadable from Nim.

<a id="orgd19ee52"></a>

# A CUBIN loader in Nim

Now we come to something closer to a reduced example. Here's the same
code as the C version from Nim:

```nim
import nimcuda/cuda12_5/[cuda, check]

proc main =
  var device: CUdevice
  var context: CUcontext
  var modul: CUmodule
  var kernel: CUfunction
  var output: CUdeviceptr

  # Init
  check cuInit(0)
  check cuDeviceGet(addr device, 0)
  check cuCtxCreate(addr context, 0, device)

  # Load the CUBIN
  let res = cuModuleLoadData(addr modul, cstring "kernel_nim.cubin")
  if res != CUDA_SUCCESS: # 
    var error_str: cstring
    discard cuGetErrorString(res, cast[cstringArray](addr error_str))
    echo "Failed to load module: ", error_str
    quit(1)

  if cuModuleGetFunction(addr kernel, modul, "warpTest") != CUDA_SUCCESS:
    echo "Failed to get function"
    quit(1)

  # Allocate GPU memory
  check cuMemAlloc(addr output, sizeof(cint) * 32)

  # Launch kernel
  var args = [cast[pointer](addr output)]
  check cuLaunchKernel(kernel,
                       1, 1, 1,    # Grid dimensions
                       32, 1, 1,   # Block dimensions
                       0, nil,       # Shared memory and stream
                       addr args[0], nil)   # Arguments and extra

  check cuCtxSynchronize()

  # Read back results
  var host_output = newSeq[cint](32)
  check cuMemcpyDtoH(addr host_output[0], output, sizeof(cint) * 32)

  # Print first few results
  for i in 0 ..< 10:
    stdout.write host_output[i], " "
  echo ""

  # Cleanup
  check cuMemFree(output)
  check cuModuleUnload(modul)
  check cuCtxDestroy(context)

main()
```

This fails with the aforementioned `CUDA_ERROR_INVALID_IMAGE` error.

<a id="org69b5e20"></a>

# A standalone example

At this point I was rather convinced the reason has to be in some
minor detail regarding the CUDA wrapper. So I wrote a standalone CUBIN
loader + wrapper script.

In the below you'll see me either using the approach of `nimcuda`
currently **or** by passing the paths to the header files and libraries
and using the `header` pragma. The latter (commented out) version
works correctly.

```nim
# Necessary if we use the `header` pragma (see below)
#{.passC: "-I/usr/local/cuda-12.6/targets/x86_64-linux/include".}
#{.passL: "-L/usr/local/cuda-12.6/targets/x86_64-linux/lib -lcuda".}

type
  CUresult* {.size: sizeof(cint).} = enum # just remove all others for the time being
    CUDA_SUCCESS = 0
    CUDA_ERROR_INVALID_IMAGE = 200
    CUDA_ERROR_UNKNOWN = 999

  CUdevice* = distinct int32
    ## Compute Device handle
  CUcontext* = distinct pointer
#  CUmodule* = distinct pointer # neither this approach
  CUfunction* = distinct pointer
  CUstream* = distinct pointer
  CUdeviceptr* = distinct pointer

# Nor this one makes a difference
type
  CUmod_st {.pure, inheritable.} = object  # Opaque struct
  CUmodule* = ptr CUmod_st                 # Matches CUDA's definition exactly

# The important piece of the puzzle is the `header` pragma
{.push importc, dynlib: "libcuda.so".} #, header: "cuda.h".}
# {.push importc, dynlib: "libcuda.so", header: "cuda.h".}

proc cuInit*(flags: uint32): CUresult
proc cuDeviceGet*(device: var CUdevice, ordinal: int32): CUresult
proc cuCtxCreate*(pctx: var CUcontext, flags: uint32, dev: CUdevice): CUresult
proc cuCtxDestroy*(ctx: CUcontext): CUresult
# correspondingly this or
#proc cuModuleLoad*(module: var CUmodule, file: cstring): CUresult {.used.}
# this
proc cuModuleLoad*(module: ptr CUmodule, file: cstring): CUresult
proc cuModuleUnload*(module: CUmodule): CUresult
proc cuMemFree*(devptr: CUdeviceptr): CUresult

{.pop.} # {.push noconv, importc, dynlib: "libcuda.so".}

template check*(status: CUresult) =
  ## Check the status code of a CUDA operation
  ## Exit program with error if failure

  let code = status # ensure that the input expression is evaluated once only
  if code != CUDA_SUCCESS:
    writeStackTrace()
    stderr.write(astToStr(status) & " " & $instantiationInfo() & " exited with error: " & $code & '\n')
    quit 1

proc main =
  var device: CUdevice
  var context: CUcontext
  var modul: CUmodule
  var kernel: CUfunction
  var output: CUdeviceptr

  # Init (all these 3 pass; I leave out `check` to produce less noise in the generated C code)
  discard cuInit(0)
  discard cuDeviceGet(device, 0)
  discard cuCtxCreate(context, 0, device)

  # Load the CUBIN
  let res = cuModuleLoad(addr modul, cstring "kernel_nim.cubin")
  if res != CUDA_SUCCESS: # fails unless we push the `header` pragma
    echo "Failed to load module ", res
    quit(1)

  # Cleanup
  check cuMemFree(output)
  check cuModuleUnload(modul)
  check cuCtxDestroy(context)

main()
```

<a id="org3e0c1f3"></a>

# Applying this to `nimcuda`

To apply this to `nimcuda` we essentially just have to push / pop the
`header` to all the wrapped procs. I've verified that this works
locally.

The downside to this approach is that we then need to pass the path to
the header at compile time. Still, I guess that's a sane trade-off for
having actually working code?

I don't fully understand why this is such a big problem with CUDA, to be 
honest. I can only assume there is some minor ABI mismatch that I don't
see. Or CUDA just does too much magic behind the scenes. :)

**Comment by lilkeet** [comment]
This is gonna give me a headache...
It appears that `printf` is a built-in function in cuda, declared internally in `common_function.h`. This header also includes fan favorites like `new`, `delete`, `free`, `malloc`, and more. It was eventually compiled in `libnvrtc-builtins.so` and gets auto-included to nvrtc programs via a header called `__nv_nvrtc_builtin_header.h`. I have confirmed that all of these cause the same issue. What this has to do with anything, i dont know.
At least its an easy fix?

**Comment by Vindaar** [comment]
> This header also includes fan favorites like `new`, `delete`, `free`, `malloc`, and more. It was eventually compiled in `libnvrtc-builtins.so` and gets auto-included to nvrtc programs via a header called `__nv_nvrtc_builtin_header.h`. I have confirmed that all of these cause the same issue. What this has to do with anything, i dont know. At least its an easy fix?

Yeah, I assumed that there would likely be other functions causing the same problem. Thanks for investigating and confirming it!

The main problem I see is how we want to handle the path to the CUDA libraries at compile time. Try to find a path? Require the user to define the path themselves? Not sure what the cleanest option looks like.

**Comment by mratsim** [comment]
Maybe we can assume that the header is in the path and use `header: "<cuda.h>"`?

**Comment by lilkeet** [comment]
> Maybe we can assume that the header is in the path and use `header: "<cuda.h>"`?

At least on my machine, this doesnt work. nvidia's docs dont have the user put the includes or libs on path anyways.

imo, the best option would be a strdefine that auto detects on the most common setups

**Comment by mratsim** [comment]
It seems like the rootcause is using cuCtxCreate instead of cuCtxCreate_v2,
see:
- https://stackoverflow.com/a/22634798

<img width="918" height="625" alt="Image" src="https://github.com/user-attachments/assets/6eb059f9-51d7-41e2-bf58-7137034d4162" />

<img width="941" height="360" alt="Image" src="https://github.com/user-attachments/assets/eb69a1b5-a3b8-4466-b7f3-95361a4d8663" />
